[theme]
# 기본 색상 설정
primaryColor = "#1f77b4"          # 파란색 (차트 및 버튼)
backgroundColor = "#ffffff"        # 흰색 배경
secondaryBackgroundColor = "#f0f2f6"  # 회색 배경 (사이드바 등)
textColor = "#262730"             # 진회색 텍스트

[server]
# 서버 설정
port = 8501
headless = false
runOnSave = true
allowRunOnSave = true
enableCORS = false
enableXsrfProtection = true

[browser]
# 브라우저 설정
gatherUsageStats = false
serverAddress = "localhost"

[client]
# 클라이언트 설정
caching = true
displayEnabled = true
showErrorDetails = true

[logger]
# 로깅 설정
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[deprecation]
# 경고 설정
showfileUploaderEncoding = false
showPyplotGlobalUse = false 